name: Test and Deploy via FTP

on:
  push


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
            vendor/bin/phpunit
            # copy outputs into the workspace for deployment
            mkdir -p ./artifacts
            cp -r config public src vendor ./artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-artifacts
          path: ./artifacts

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: application-artifacts

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            .devcontainer*/**
            .sql*/**
            .vscode*/**
            .env.*
            README.md
            composer.*
